### ISSUE TITLE
Some SSH settings not configurable with the role

### ISSUE THREAD

**Issue by bschonec** [siw36/ansible-ssh-hardening#1]
Case in point:  LogLevel, SyslogFacility.

Do you have any standard naming conventions you want me to adhere to when I submit a  merge request?

I'm thinking:  log_level and syslog_facility

**Comment by siw36** [comment]
I'm using prefixed lower camel case for variables. So those would be `sshLogLevel` and `sshSyslogFacility`.
Feel free to create a PR and include me as a reviewer.
